/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/info/About.vue')['default']
    FooterArea: typeof import('./src/components/FooterArea.vue')['default']
    HeaderArea: typeof import('./src/components/HeaderArea.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconTask: typeof import('./src/assets/icons/IconTask.vue')['default']
    InfoView: typeof import('./src/views/InfoView.vue')['default']
    LeftSideBar: typeof import('./src/views/LeftSideBar.vue')['default']
    PluginTab: typeof import('./src/components/plugins/PluginTab.vue')['default']
    PluginView: typeof import('./src/views/PluginView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingView: typeof import('./src/views/SettingView.vue')['default']
    TabLeftSideBar: typeof import('./src/components/TabLeftSideBar.vue')['default']
    TaskTab: typeof import('./src/components/tasks/TaskTab.vue')['default']
    TaskView: typeof import('./src/views/TaskView.vue')['default']
    Update: typeof import('./src/components/info/Update.vue')['default']
    Use: typeof import('./src/components/info/Use.vue')['default']
  }
}
