// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {shared} from '../models';
import {emptypb} from '../models';
import {proto} from '../models';

export function AddDownloadTasks(arg1:Array<app.taskMap>):Promise<boolean>;

export function GetConfig():Promise<app.Config>;

export function GetPlugins():Promise<Array<app.Plugin>>;

export function GetTaskParts():Promise<Array<shared.Part>>;

export function InitPlugin():Promise<emptypb.Empty>;

export function OpenExplorer(arg1:string):Promise<void>;

export function OpenFileWithSystemPlayer(arg1:string):Promise<void>;

export function ParsePlaylist(arg1:Array<string>):Promise<proto.ParseResponse>;

export function RemoveAllTask(arg1:Array<shared.Part>):Promise<boolean>;

export function RemoveTask(arg1:string):Promise<boolean>;

export function SaveConfig(arg1:app.Config):Promise<boolean>;

export function SetDownloadDir(arg1:string):Promise<string>;

export function ShowDownloadInfo(arg1:string):Promise<proto.InfoResponse>;

export function UpdatePlugin():Promise<emptypb.Empty>;
