// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {shared} from '../models';
import {app} from '../models';

export function AddDownloadTasks(arg1:Array<proto.Task>):Promise<Array<shared.Part>>;

export function GetConfig():Promise<app.Config>;

export function GetTaskParts():Promise<Array<shared.Part>>;

export function OpenExplorer(arg1:string):Promise<void>;

export function OpenFileWithSystemPlayer(arg1:string):Promise<void>;

export function ParsePlaylist(arg1:Array<string>):Promise<proto.ParseResponse>;

export function RemoveAllTask(arg1:Array<shared.Part>):Promise<boolean>;

export function RemoveTask(arg1:string):Promise<boolean>;

export function SaveConfig(arg1:app.Config):Promise<boolean>;

export function SetDownloadDir(arg1:string):Promise<string>;

export function ShowDownloadInfo(arg1:string):Promise<proto.VideoInfoResponse>;
