// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {proto} from '../models';

export function AddDownloadTasks(arg1:Array<app.taskMap>):Promise<boolean>;

export function DisablePlugin(arg1:app.Plugin):Promise<app.Plugin>;

export function DownloadPlugin(arg1:app.Plugin):Promise<app.Plugin>;

export function EnablePlugin(arg1:app.Plugin):Promise<app.Plugin|string>;

export function GetConfig():Promise<app.Config>;

export function GetPlugins():Promise<{[key: string]: app.Plugin}>;

export function OpenExplorer(arg1:string):Promise<void>;

export function OpenFileWithSystemPlayer(arg1:string):Promise<void>;

export function ParsePlaylist(arg1:Array<string>):Promise<proto.ParseResponse>;

export function RemoveAllTask(arg1:Array<app.Part>):Promise<boolean>;

export function RemoveTask(arg1:string):Promise<boolean>;

export function RunPlugin(arg1:app.Plugin):Promise<app.Plugin>;

export function SaveConfig(arg1:app.Config):Promise<boolean>;

export function SavePluginConfig(arg1:string,arg2:app.PluginConfig):Promise<app.Plugin>;

export function SetDownloadDir(arg1:string):Promise<string>;

export function ShowDownloadInfo(arg1:string):Promise<proto.InfoResponse>;

export function StopPlugin(arg1:app.Plugin):Promise<app.Plugin>;

export function TaskParts():Promise<Array<app.Part>>;

export function UpdatePlugin(arg1:app.Plugin):Promise<app.Plugin>;

export function UpdatePluginsConfig(arg1:string,arg2:app.PluginConfig):Promise<app.App>;

export function UpdateSystemConfig(arg1:app.SystemConfig):Promise<app.App>;
