// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadTasks(arg1) {
  return window['go']['app']['App']['AddDownloadTasks'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetPlugins() {
  return window['go']['app']['App']['GetPlugins']();
}

export function GetTaskParts() {
  return window['go']['app']['App']['GetTaskParts']();
}

export function InitPlugin() {
  return window['go']['app']['App']['InitPlugin']();
}

export function OpenExplorer(arg1) {
  return window['go']['app']['App']['OpenExplorer'](arg1);
}

export function OpenFileWithSystemPlayer(arg1) {
  return window['go']['app']['App']['OpenFileWithSystemPlayer'](arg1);
}

export function ParsePlaylist(arg1) {
  return window['go']['app']['App']['ParsePlaylist'](arg1);
}

export function RemoveAllTask(arg1) {
  return window['go']['app']['App']['RemoveAllTask'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['app']['App']['RemoveTask'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SetDownloadDir(arg1) {
  return window['go']['app']['App']['SetDownloadDir'](arg1);
}

export function ShowDownloadInfo(arg1) {
  return window['go']['app']['App']['ShowDownloadInfo'](arg1);
}

export function UpdatePlugin() {
  return window['go']['app']['App']['UpdatePlugin']();
}
